name: Fortify

# Controls when the workflow will run
on:
   workflow_dispatch:
         

jobs:
   build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
          
      - name: clean the repo
        run: 
          rm -rf /samplecode/demo/script.sh
          
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Run a one-line script
        run: java --version

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
         
          java --version
        
