name: Fortify

# Controls when the workflow will run
on:
   push:
      branches:
         main
         

jobs:
   build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
          
      - name: clean the repo
        run: 
          rm -rf /samplecode/demo/script.sh
          
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - name: Run a one-line script
        run: java --version

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          
          wget -o $RUNNER_TEMP/fcli.jar "https://github.com/fortify/fcli/releases/download/v2.4.0/fcli.jar"
          java -jar fcli.jar --version
          java -jar fcli.jar fod sast scan session login -u arpitha -p password -t sample --url -k https://ams.fortify.com
        
